export interface IndianFoodItem {
  id: string;
  name: string;
  hindiName: string;
  category: 'staple' | 'curry' | 'south_indian' | 'snack' | 'protein' | 'dessert' | 'beverage';
  diet: 'veg' | 'jain' | 'eggetarian' | 'non_veg';
  servingSize: string;
  calories: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
  fiberG: number;
  costInr: number;
  glycemicIndex: 'Low' | 'Medium' | 'High';
  nutritionTip: string;
}

export const INDIAN_FOOD_DATABASE: IndianFoodItem[] = [
  // ================= STAPLES & ROTIS =================
  {
    id: 'roti_plain',
    name: 'Plain Phulka / Whole Wheat Roti',
    hindiName: 'सादा फुल्का / गेहूं की रोटी',
    category: 'staple',
    diet: 'veg',
    servingSize: '1 Medium Roti (30g flour)',
    calories: 85,
    proteinG: 3.1,
    carbsG: 17.5,
    fatG: 0.5,
    fiberG: 2.3,
    costInr: 2,
    glycemicIndex: 'Medium',
    nutritionTip: 'Complex whole wheat grain provides sustained release beta-glucans and B vitamins.',
  },
  {
    id: 'roti_ghee',
    name: 'Phulka with 1/2 tsp Desi Ghee',
    hindiName: 'देसी घी लगी रोटी',
    category: 'staple',
    diet: 'veg',
    servingSize: '1 Medium Roti + 2.5g Ghee',
    calories: 110,
    proteinG: 3.1,
    carbsG: 17.5,
    fatG: 3.2,
    fiberG: 2.3,
    costInr: 5,
    glycemicIndex: 'Low',
    nutritionTip: 'Desi ghee slows carbohydrate gastric clearance, reducing the postprandial insulin spike by 22%.',
  },
  {
    id: 'jowar_roti',
    name: 'Jowar (Sorghum) Bhakri Roti',
    hindiName: 'ज्वार की रोटी',
    category: 'staple',
    diet: 'veg',
    servingSize: '1 Medium Bhakri (40g flour)',
    calories: 120,
    proteinG: 4.2,
    carbsG: 26.0,
    fatG: 1.0,
    fiberG: 4.8,
    costInr: 6,
    glycemicIndex: 'Low',
    nutritionTip: '100% Gluten-free millet powerhouse rich in resistant starch and polyphenols.',
  },
  {
    id: 'bajra_roti',
    name: 'Bajra (Pearl Millet) Roti',
    hindiName: 'बाजरे की रोटी',
    category: 'staple',
    diet: 'veg',
    servingSize: '1 Medium Roti (40g flour)',
    calories: 135,
    proteinG: 4.6,
    carbsG: 27.0,
    fatG: 1.8,
    fiberG: 5.2,
    costInr: 6,
    glycemicIndex: 'Low',
    nutritionTip: 'Exceptional source of non-heme iron and magnesium, ideal for winter thermogenesis.',
  },
  {
    id: 'steamed_rice_white',
    name: 'Steamed White Basmati Rice',
    hindiName: 'उबले सफेद चावल',
    category: 'staple',
    diet: 'veg',
    servingSize: '1 Standard Katori (150g cooked)',
    calories: 195,
    proteinG: 4.1,
    carbsG: 43.0,
    fatG: 0.4,
    fiberG: 0.8,
    costInr: 8,
    glycemicIndex: 'High',
    nutritionTip: 'Pair with high-protein Dal or Rajma to create a complete amino acid profile.',
  },
  {
    id: 'steamed_rice_brown',
    name: 'Steamed Brown Rice',
    hindiName: 'ब्राउन राइस (उबले)',
    category: 'staple',
    diet: 'veg',
    servingSize: '1 Standard Katori (150g cooked)',
    calories: 165,
    proteinG: 4.5,
    carbsG: 34.0,
    fatG: 1.2,
    fiberG: 3.5,
    costInr: 14,
    glycemicIndex: 'Medium',
    nutritionTip: 'Retains the fiber-rich bran and germ layer containing manganese and magnesium.',
  },
  {
    id: 'dal_khichdi',
    name: 'Moong Dal Khichdi with Ghee',
    hindiName: 'मूंग दाल खिचड़ी',
    category: 'staple',
    diet: 'veg',
    servingSize: '1 Big Bowl (250g)',
    calories: 280,
    proteinG: 11.5,
    carbsG: 46.0,
    fatG: 6.0,
    fiberG: 5.5,
    costInr: 18,
    glycemicIndex: 'Medium',
    nutritionTip: 'The ultimate Ayurvedic restorative meal, extremely gentle on gut microflora.',
  },

  // ================= DALS & CURRIES =================
  {
    id: 'yellow_moong_dal',
    name: 'Yellow Moong Dal Tadka (Home Style)',
    hindiName: 'पीली मूंग दाल तड़का',
    category: 'curry',
    diet: 'veg',
    servingSize: '1 Standard Katori (150ml)',
    calories: 145,
    proteinG: 9.2,
    carbsG: 19.5,
    fatG: 3.5,
    fiberG: 4.5,
    costInr: 12,
    glycemicIndex: 'Low',
    nutritionTip: 'Lightest legume on the digestive system with high folate and potassium content.',
  },
  {
    id: 'dal_makhani_dhaba',
    name: 'Dhaba Style Dal Makhani (Butter & Cream)',
    hindiName: 'दाल मखनी (मक्खन और क्रीम)',
    category: 'curry',
    diet: 'veg',
    servingSize: '1 Standard Katori (180ml)',
    calories: 340,
    proteinG: 11.0,
    carbsG: 28.0,
    fatG: 21.0,
    fiberG: 6.5,
    costInr: 45,
    glycemicIndex: 'Medium',
    nutritionTip: 'High caloric density due to butter/cream; enjoy in moderation during refeed days.',
  },
  {
    id: 'rajma_masala',
    name: 'Punjabi Rajma Masala (Red Kidney Beans)',
    hindiName: 'पंजाबी राजमा मसाला',
    category: 'curry',
    diet: 'veg',
    servingSize: '1 Big Bowl (200ml)',
    calories: 220,
    proteinG: 13.5,
    carbsG: 34.0,
    fatG: 4.5,
    fiberG: 9.5,
    costInr: 22,
    glycemicIndex: 'Low',
    nutritionTip: 'Loaded with soluble fiber that binds to bile salts and naturally lowers serum cholesterol.',
  },
  {
    id: 'chole_masala',
    name: 'Amritsari Chole (Kabuli Chickpeas)',
    hindiName: 'अमृतसरी छोले',
    category: 'curry',
    diet: 'veg',
    servingSize: '1 Big Bowl (200ml)',
    calories: 260,
    proteinG: 14.2,
    carbsG: 38.0,
    fatG: 6.5,
    fiberG: 10.5,
    costInr: 25,
    glycemicIndex: 'Low',
    nutritionTip: 'Contains choline and prebiotic oligosaccharides that boost brain neurotransmitter synthesis.',
  },
  {
    id: 'paneer_butter_masala',
    name: 'Paneer Butter Masala (Restaurant Gravy)',
    hindiName: 'पनीर बटर मसाला',
    category: 'curry',
    diet: 'veg',
    servingSize: '1 Standard Bowl (180g)',
    calories: 390,
    proteinG: 16.5,
    carbsG: 14.0,
    fatG: 31.0,
    fiberG: 2.5,
    costInr: 75,
    glycemicIndex: 'Medium',
    nutritionTip: 'Rich in dairy calcium, but high in saturated fats from cashew paste and butter.',
  },
  {
    id: 'palak_paneer_home',
    name: 'Healthy Home Palak Paneer',
    hindiName: 'घर का पालक पनीर',
    category: 'curry',
    diet: 'veg',
    servingSize: '1 Big Bowl (200g)',
    calories: 240,
    proteinG: 17.5,
    carbsG: 9.0,
    fatG: 15.5,
    fiberG: 5.5,
    costInr: 42,
    glycemicIndex: 'Low',
    nutritionTip: 'Synergistic combination: calcium from paneer + magnesium, lutein & iron from spinach.',
  },
  {
    id: 'soya_chunk_curry',
    name: 'High-Protein Soya Chunk Curry',
    hindiName: 'सोया चंक्स करी',
    category: 'curry',
    diet: 'veg',
    servingSize: '1 Big Bowl (50g dry soya)',
    calories: 220,
    proteinG: 26.5,
    carbsG: 16.0,
    fatG: 4.5,
    fiberG: 7.5,
    costInr: 16,
    glycemicIndex: 'Low',
    nutritionTip: 'The #1 cost-to-protein ratio in Indian nutrition: 52g protein per 100g dry weight.',
  },
  {
    id: 'chicken_curry_home',
    name: 'Home-Style Chicken Breast Curry',
    hindiName: 'घर की चिकन करी',
    category: 'curry',
    diet: 'non_veg',
    servingSize: '1 Big Bowl (150g chicken)',
    calories: 275,
    proteinG: 38.0,
    carbsG: 6.0,
    fatG: 11.0,
    fiberG: 1.5,
    costInr: 65,
    glycemicIndex: 'Low',
    nutritionTip: 'Zero carbohydrate lean protein source packed with creatine and bioavailable heme-iron.',
  },
  {
    id: 'egg_curry_2eggs',
    name: 'Dhaba Egg Curry (2 Whole Eggs)',
    hindiName: 'अंडा करी (2 अंडे)',
    category: 'curry',
    diet: 'eggetarian',
    servingSize: '2 Eggs + Gravy',
    calories: 230,
    proteinG: 14.5,
    carbsG: 7.0,
    fatG: 16.0,
    fiberG: 1.5,
    costInr: 25,
    glycemicIndex: 'Low',
    nutritionTip: 'Complete amino acid score with active lutein, zeaxanthin and choline for brain cognition.',
  },

  // ================= SOUTH INDIAN STAPLES =================
  {
    id: 'idli_sambar_2pcs',
    name: 'Steamed Rice & Urad Dal Idli (2 Pcs) + Sambar',
    hindiName: 'इडली और सांभर (2 पीस)',
    category: 'south_indian',
    diet: 'veg',
    servingSize: '2 Medium Idlis + 150ml Sambar',
    calories: 210,
    proteinG: 7.8,
    carbsG: 41.0,
    fatG: 2.1,
    fiberG: 4.5,
    costInr: 25,
    glycemicIndex: 'Medium',
    nutritionTip: 'Naturally fermented with live wild lactobacilli, boosting B-complex vitamin synthesis.',
  },
  {
    id: 'plain_dosa_sambar',
    name: 'Crispy Plain Dosa + Sambar (No Chutney)',
    hindiName: 'प्लेन डोसा और सांभर',
    category: 'south_indian',
    diet: 'veg',
    servingSize: '1 Large Dosa + 150ml Sambar',
    calories: 260,
    proteinG: 6.5,
    carbsG: 48.0,
    fatG: 5.5,
    fiberG: 3.5,
    costInr: 30,
    glycemicIndex: 'Medium',
    nutritionTip: 'Fermented batter improves mineral bioaccessibility while retaining a light crisp texture.',
  },
  {
    id: 'masala_dosa_aloo',
    name: 'Masala Dosa with Potato Filling + Coconut Chutney',
    hindiName: 'मसाला डोसा और नारियल चटनी',
    category: 'south_indian',
    diet: 'veg',
    servingSize: '1 Large Masala Dosa + Chutneys',
    calories: 420,
    proteinG: 8.5,
    carbsG: 64.0,
    fatG: 15.0,
    fiberG: 5.0,
    costInr: 50,
    glycemicIndex: 'High',
    nutritionTip: 'High carb energy meal; coconut chutney provides medium chain triglycerides (MCTs).',
  },
  {
    id: 'poha_roasted_peanuts',
    name: 'Indori Kanda Poha with Peanuts & Lemon',
    hindiName: 'कांदा पोहा और मूंगफली',
    category: 'south_indian',
    diet: 'veg',
    servingSize: '1 Medium Plate (180g)',
    calories: 290,
    proteinG: 7.5,
    carbsG: 48.0,
    fatG: 8.5,
    fiberG: 3.8,
    costInr: 16,
    glycemicIndex: 'Medium',
    nutritionTip: 'Flattened rice absorbs iron from iron rollers during traditional manufacturing processing.',
  },

  // ================= INDIAN HIGH-PROTEIN SNACKS =================
  {
    id: 'chana_sattu_drink',
    name: 'Bihari Chana Sattu Drink (Water + Lemon + Jeera)',
    hindiName: 'चना सत्तू शरबत',
    category: 'protein',
    diet: 'veg',
    servingSize: '1 Glass (45g Sattu + 250ml Water)',
    calories: 180,
    proteinG: 15.5,
    carbsG: 24.0,
    fatG: 2.8,
    fiberG: 6.8,
    costInr: 11,
    glycemicIndex: 'Low',
    nutritionTip: 'Indigenous super-protein: 0 cholesterol, cooling electrolyte balance, long-lasting fullness.',
  },
  {
    id: 'roasted_kala_chana',
    name: 'Roasted Bengal Gram (Bhuna Chana with Skin)',
    hindiName: 'भुना चना (छिलके सहित)',
    category: 'protein',
    diet: 'veg',
    servingSize: '1 Handful (50g)',
    calories: 190,
    proteinG: 12.5,
    carbsG: 28.0,
    fatG: 2.9,
    fiberG: 8.5,
    costInr: 10,
    glycemicIndex: 'Low',
    nutritionTip: 'Lowest glycemic index snack in the world (GI = 28); perfect for fat loss deskside snacking.',
  },
  {
    id: 'boiled_eggs_3whole',
    name: '3 Hard-Boiled Whole Eggs with Black Pepper',
    hindiName: '3 उबले अंडे (काली मिर्च)',
    category: 'protein',
    diet: 'eggetarian',
    servingSize: '3 Large Eggs',
    calories: 215,
    proteinG: 18.5,
    carbsG: 1.2,
    fatG: 15.0,
    fiberG: 0,
    costInr: 21,
    glycemicIndex: 'Low',
    nutritionTip: 'Golden standard of biological value (BV=100); lutein and choline reside in yolk.',
  },
  {
    id: 'egg_whites_4boiled',
    name: '4 Boiled Egg Whites (Zero Yolk)',
    hindiName: '4 उबले अंडे की सफेदी',
    category: 'protein',
    diet: 'eggetarian',
    servingSize: '4 Egg Whites (130g)',
    calories: 70,
    proteinG: 14.8,
    carbsG: 0.9,
    fatG: 0.2,
    fiberG: 0,
    costInr: 24,
    glycemicIndex: 'Low',
    nutritionTip: 'Pure protein with 0 fat and 0 carbs, the most calorie-efficient muscle recovery fuel.',
  },
  {
    id: 'paneer_raw_cubes',
    name: 'Fresh Cow Milk Paneer (Raw Cubes)',
    hindiName: 'ताजा पनीर (कच्चा)',
    category: 'protein',
    diet: 'veg',
    servingSize: '100g Cubes',
    calories: 265,
    proteinG: 18.3,
    carbsG: 3.2,
    fatG: 20.8,
    fiberG: 0,
    costInr: 40,
    glycemicIndex: 'Low',
    nutritionTip: 'Rich in slow-digesting micellar casein and bioavailable conjugated linoleic acid (CLA).',
  },
  {
    id: 'soya_bhurji_stir',
    name: 'High-Protein Soya Granule Bhurji',
    hindiName: 'सोया भुर्जी',
    category: 'protein',
    diet: 'veg',
    servingSize: '1 Plate (60g dry granules)',
    calories: 225,
    proteinG: 32.5,
    carbsG: 14.0,
    fatG: 3.8,
    fiberG: 8.2,
    costInr: 18,
    glycemicIndex: 'Low',
    nutritionTip: 'Delivers 32g complete plant protein for only ₹18; vegetarian hypertrophy gold standard.',
  },

  // ================= INDIAN STREET FOOD & CHEAT MEALS =================
  {
    id: 'samosa_fried',
    name: 'Fried Potato Samosa (1 Pc)',
    hindiName: 'समोसा (1 पीस)',
    category: 'snack',
    diet: 'veg',
    servingSize: '1 Standard Samosa (90g)',
    calories: 260,
    proteinG: 4.2,
    carbsG: 32.0,
    fatG: 14.5,
    fiberG: 2.1,
    costInr: 15,
    glycemicIndex: 'High',
    nutritionTip: 'Deep fried refined flour (maida) + spiced potato; enjoy during scheduled cheat meals.',
  },
  {
    id: 'pani_puri_6pcs',
    name: 'Golgappa / Pani Puri (6 Pcs with Teekha Paani)',
    hindiName: 'पानी पूरी / गोलगप्पे (6 पीस)',
    category: 'snack',
    diet: 'veg',
    servingSize: '6 Puris with Spiced Water',
    calories: 190,
    proteinG: 3.8,
    carbsG: 34.0,
    fatG: 4.5,
    fiberG: 2.5,
    costInr: 30,
    glycemicIndex: 'Medium',
    nutritionTip: 'Hing, mint, cumin and black salt in teekha pani act as carminative digestive stimulants.',
  },
  {
    id: 'pav_bhaji_butter',
    name: 'Mumbai Pav Bhaji (2 Buttered Pavs + Bhaji)',
    hindiName: 'पाव भाजी (2 पाव)',
    category: 'snack',
    diet: 'veg',
    servingSize: '2 Butter Pavs + 1 Bowl Bhaji',
    calories: 540,
    proteinG: 10.5,
    carbsG: 68.0,
    fatG: 26.0,
    fiberG: 6.5,
    costInr: 80,
    glycemicIndex: 'High',
    nutritionTip: 'High glycemic load from white pav and butter; offset with 25 minutes brisk walking.',
  },
  {
    id: 'chole_bhature_2pcs',
    name: 'Amritsari Chole Bhature (2 Fried Bhature + Chole)',
    hindiName: 'छोले भटूरे (2 भटूरे)',
    category: 'snack',
    diet: 'veg',
    servingSize: '2 Bhature + 1 Big Bowl Chole',
    calories: 780,
    proteinG: 22.0,
    carbsG: 96.0,
    fatG: 36.0,
    fiberG: 12.0,
    costInr: 90,
    glycemicIndex: 'High',
    nutritionTip: 'Heavy cheat meal; plan a 200 kcal pre-bank calorie buffer before indulging.',
  },

  // ================= INDIAN DESSERTS & SWEETS =================
  {
    id: 'gulab_jamun_2pcs',
    name: 'Khowa Gulab Jamun in Sugar Syrup (2 Pcs)',
    hindiName: 'गुलाब जामुन (2 पीस)',
    category: 'dessert',
    diet: 'veg',
    servingSize: '2 Standard Pieces (80g)',
    calories: 320,
    proteinG: 5.5,
    carbsG: 52.0,
    fatG: 11.5,
    fiberG: 0.4,
    costInr: 35,
    glycemicIndex: 'High',
    nutritionTip: 'Pure sucrose and concentrated milk solids; spike insulin rapidly.',
  },
  {
    id: 'kaju_katli_2pcs',
    name: 'Silver Vark Kaju Katli (2 Diamonds)',
    hindiName: 'काजू कतली (2 पीस)',
    category: 'dessert',
    diet: 'veg',
    servingSize: '2 Pieces (30g)',
    calories: 145,
    proteinG: 3.2,
    carbsG: 18.0,
    fatG: 7.2,
    fiberG: 0.6,
    costInr: 40,
    glycemicIndex: 'Medium',
    nutritionTip: 'Cashew base provides monounsaturated fatty acids and copper alongside sweetness.',
  },

  // ================= BEVERAGES & DAIRY =================
  {
    id: 'masala_chai_sugar',
    name: 'Indian Masala Cutting Chai (with 1.5 tsp sugar)',
    hindiName: 'मसाला चाय (चीनी सहित)',
    category: 'beverage',
    diet: 'veg',
    servingSize: '1 Cup (150ml)',
    calories: 95,
    proteinG: 2.8,
    carbsG: 14.5,
    fatG: 3.1,
    fiberG: 0,
    costInr: 10,
    glycemicIndex: 'Medium',
    nutritionTip: 'Ginger and cardamom provide thermogenic gingerols and cineole; switch to stevia for 0 kcal.',
  },
  {
    id: 'desi_chaas_jeera',
    name: 'Masala Buttermilk (Chaas with Roasted Jeera)',
    hindiName: 'मसाला छाछ (जीरा)',
    category: 'beverage',
    diet: 'veg',
    servingSize: '1 Big Glass (300ml)',
    calories: 55,
    proteinG: 3.8,
    carbsG: 5.2,
    fatG: 1.8,
    fiberG: 0.5,
    costInr: 8,
    glycemicIndex: 'Low',
    nutritionTip: 'The king of Indian hydration: sodium, potassium, and active live probiotic strains.',
  },
  {
    id: 'coconut_water_fresh',
    name: 'Fresh Green Coconut Water (Nariyal Paani)',
    hindiName: 'ताजा नारियल पानी',
    category: 'beverage',
    diet: 'veg',
    servingSize: '1 Whole Coconut (250ml)',
    calories: 48,
    proteinG: 1.8,
    carbsG: 9.8,
    fatG: 0.5,
    fiberG: 1.2,
    costInr: 50,
    glycemicIndex: 'Low',
    nutritionTip: 'Identical electrolyte osmolarity to human blood plasma with zero artificial sweeteners.',
  },
];

export const searchIndianFoodDatabase = (query: string): IndianFoodItem[] => {
  const cleanQuery = query.toLowerCase().trim();
  if (!cleanQuery) return INDIAN_FOOD_DATABASE.slice(0, 15);

  return INDIAN_FOOD_DATABASE.filter((item) => {
    const nameMatch = item.name.toLowerCase().includes(cleanQuery);
    const hindiMatch = item.hindiName.toLowerCase().includes(cleanQuery);
    const categoryMatch = item.category.toLowerCase().includes(cleanQuery);
    return nameMatch || hindiMatch || categoryMatch;
  });
};
