import React from 'react';
import {
  View,
  Text,
  Modal,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  Share,
  Alert,
} from 'react-native';
import { useTheme } from '../context/ThemeContext';
import { useAuth } from '../context/AuthContext';
import {
  X,
  Sparkles,
  Activity,
  Zap,
  TrendingDown,
  Scale,
  ShieldCheck,
  Share2,
  FileText,
  ShoppingBag,
  Heart,
  Layers,
  ArrowRight,
  Flame,
  Clock,
  CheckCircle2,
} from 'lucide-react-native';

export type PerkType =
  | 'perk_metabolic_dexa'
  | 'perk_glucose_guard'
  | 'perk_kirana_mandi'
  | 'perk_micronutrient_boost'
  | 'perk_clinical_pdf';

interface UnlockedPerkViewerModalProps {
  visible: boolean;
  onClose: () => void;
  perkType: PerkType;
}

export const UnlockedPerkViewerModal: React.FC<UnlockedPerkViewerModalProps> = ({
  visible,
  onClose,
  perkType,
}) => {
  const { theme } = useTheme();
  const { user, getDayTotals } = useAuth();
  const todayTotals = getDayTotals(new Date().toISOString().split('T')[0]);

  const handleShareReport = async () => {
    try {
      await Share.share({
        message: `MealFit Clinical Progress Report for ${user.fullName}\nGoal: ${user.goalType.toUpperCase()}\nTarget Weight: ${user.targetWeightKg} kg\nDaily Calorie Target: ${user.dailyCalorieTarget} kcal\nProtein Target: ${user.proteinTargetG}g\nGenerated by MealFit India.`,
      });
    } catch (err: any) {
      Alert.alert('Share', err.message);
    }
  };

  return (
    <Modal
      visible={visible}
      animationType="slide"
      transparent
      onRequestClose={onClose}
    >
      <View style={styles.modalOverlay}>
        <View
          style={[
            styles.modalContainer,
            { backgroundColor: theme.card, borderColor: theme.cardBorder },
          ]}
        >
          {/* Header */}
          <View style={[styles.header, { borderBottomColor: theme.cardBorder }]}>
            <View style={styles.headerTitleRow}>
              <View style={[styles.iconBox, { backgroundColor: theme.primaryLight }]}>
                <Sparkles size={18} color={theme.primary} />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={[styles.headerTitle, { color: theme.textPrimary }]}>
                  {perkType === 'perk_metabolic_dexa' && 'AI DEXA & Metabolic Projection'}
                  {perkType === 'perk_glucose_guard' && 'Glycemic & Insulin Spike Sequencer'}
                  {perkType === 'perk_kirana_mandi' && 'Kirana Mandi Price Arbitrage Guide'}
                  {perkType === 'perk_micronutrient_boost' && 'Anti-Nutrient & Micronutrient Optimizer'}
                  {perkType === 'perk_clinical_pdf' && 'Clinical Transformation Summary'}
                </Text>
                <Text style={[styles.headerSub, { color: theme.textSecondary }]}>
                  VIP Discipline Reward Feature • Clinical Grade
                </Text>
              </View>
            </View>
            <TouchableOpacity onPress={onClose} style={styles.closeBtn}>
              <X size={20} color={theme.textSecondary} />
            </TouchableOpacity>
          </View>

          <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
            {/* 1. METABOLIC DEXA PROJECTION */}
            {perkType === 'perk_metabolic_dexa' && (
              <View style={styles.contentCol}>
                <View style={[styles.heroPerkCard, { backgroundColor: theme.primaryLight, borderColor: theme.primary }]}>
                  <View style={styles.cardHeaderRow}>
                    <Activity size={18} color={theme.primary} />
                    <Text style={[styles.cardHeading, { color: theme.primary }]}>
                      Metabolic Adaptation & Fat Mass Model
                    </Text>
                  </View>
                  <Text style={[styles.cardBodyText, { color: theme.textPrimary }]}>
                    Based on your Mifflin-St Jeor TDEE ({user.dailyCalorieTarget} kcal/day) and current weight of {user.weightKg} kg:
                  </Text>
                </View>

                <View style={styles.metricGrid}>
                  <View style={[styles.metricCard, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                    <TrendingDown size={18} color={theme.primary} />
                    <Text style={[styles.metricLabel, { color: theme.textMuted }]}>Projected Fat Loss</Text>
                    <Text style={[styles.metricValue, { color: theme.primary }]}>0.48 kg / week</Text>
                    <Text style={[styles.metricSub, { color: theme.textSecondary }]}>Pure Adipose Tissue</Text>
                  </View>

                  <View style={[styles.metricCard, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                    <Flame size={18} color={theme.amber} />
                    <Text style={[styles.metricLabel, { color: theme.textMuted }]}>Metabolic Slowdown Risk</Text>
                    <Text style={[styles.metricValue, { color: theme.amber }]}>Low (4.2%)</Text>
                    <Text style={[styles.metricSub, { color: theme.textSecondary }]}>Sufficient Protein Buffer</Text>
                  </View>

                  <View style={[styles.metricCard, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                    <Layers size={18} color={theme.cyan} />
                    <Text style={[styles.metricLabel, { color: theme.textMuted }]}>Visceral Fat Target</Text>
                    <Text style={[styles.metricValue, { color: theme.cyan }]}>Level 4 (Healthy)</Text>
                    <Text style={[styles.metricSub, { color: theme.textSecondary }]}>In ~{user.estimatedWeeksToGoal || 8} weeks</Text>
                  </View>

                  <View style={[styles.metricCard, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                    <Scale size={18} color={theme.indigo} />
                    <Text style={[styles.metricLabel, { color: theme.textMuted }]}>Lean Mass Retention</Text>
                    <Text style={[styles.metricValue, { color: theme.indigo }]}>96.8%</Text>
                    <Text style={[styles.metricSub, { color: theme.textSecondary }]}>With 4-phase workouts</Text>
                  </View>
                </View>

                <View style={[styles.adviceBox, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                  <Text style={[styles.adviceTitle, { color: theme.textPrimary }]}>Scientific Takeaway</Text>
                  <Text style={[styles.adviceDesc, { color: theme.textSecondary }]}>
                    Your moderate 400 kcal deficit preserves thyroid T3 conversion while optimizing lipolysis. No refeed required until week 4.
                  </Text>
                </View>
              </View>
            )}

            {/* 2. GLUCOSE & INSULIN SPIKE SEQUENCER */}
            {perkType === 'perk_glucose_guard' && (
              <View style={styles.contentCol}>
                <View style={[styles.heroPerkCard, { backgroundColor: theme.cyanLight, borderColor: theme.cyan }]}>
                  <View style={styles.cardHeaderRow}>
                    <Zap size={18} color={theme.cyan} />
                    <Text style={[styles.cardHeading, { color: theme.cyan }]}>
                      3-Step Indian Meal Sequencing Protocol
                    </Text>
                  </View>
                  <Text style={[styles.cardBodyText, { color: theme.textPrimary }]}>
                    Sequencing food order reduces post-prandial glucose spikes by up to 42% without reducing portion sizes:
                  </Text>
                </View>

                <View style={styles.stepsList}>
                  <View style={[styles.stepItem, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                    <View style={[styles.stepBadge, { backgroundColor: theme.cyan }]}>
                      <Text style={styles.stepNum}>1</Text>
                    </View>
                    <View style={{ flex: 1, gap: 2 }}>
                      <Text style={[styles.stepTitle, { color: theme.textPrimary }]}>
                        First 5 Mins: Fiber & Raw Greens
                      </Text>
                      <Text style={[styles.stepSub, { color: theme.textSecondary }]}>
                        Eat cucumber, tomato, onion with lemon. Creates a viscous mesh lining in the duodenum to slow sugar absorption.
                      </Text>
                    </View>
                  </View>

                  <View style={[styles.stepItem, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                    <View style={[styles.stepBadge, { backgroundColor: theme.primary }]}>
                      <Text style={styles.stepNum}>2</Text>
                    </View>
                    <View style={{ flex: 1, gap: 2 }}>
                      <Text style={[styles.stepTitle, { color: theme.textPrimary }]}>
                        Next 10 Mins: Protein & Healthy Fats
                      </Text>
                      <Text style={[styles.stepSub, { color: theme.textSecondary }]}>
                        Eat Paneer, Dal, Soya, Eggs or Chicken. Triggers GLP-1 hormone release for sustained satiety.
                      </Text>
                    </View>
                  </View>

                  <View style={[styles.stepItem, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                    <View style={[styles.stepBadge, { backgroundColor: theme.amber }]}>
                      <Text style={styles.stepNum}>3</Text>
                    </View>
                    <View style={{ flex: 1, gap: 2 }}>
                      <Text style={[styles.stepTitle, { color: theme.textPrimary }]}>
                        Last: Phulkas / Rice / Complex Starch
                      </Text>
                      <Text style={[styles.stepSub, { color: theme.textSecondary }]}>
                        Consume Rotis or Rice last. Glucose enters bloodstream slowly with zero insulin crash or afternoon fatigue.
                      </Text>
                    </View>
                  </View>
                </View>
              </View>
            )}

            {/* 3. KIRANA MANDI ARBITRAGE GUIDE */}
            {perkType === 'perk_kirana_mandi' && (
              <View style={styles.contentCol}>
                <View style={[styles.heroPerkCard, { backgroundColor: theme.amberLight, borderColor: theme.amber }]}>
                  <View style={styles.cardHeaderRow}>
                    <ShoppingBag size={18} color={theme.amber} />
                    <Text style={[styles.cardHeading, { color: theme.amber }]}>
                      Wholesale Indian Mandi Price Secrets
                    </Text>
                  </View>
                  <Text style={[styles.cardBodyText, { color: theme.textPrimary }]}>
                    How to get 100g daily protein for under ₹45/day by bypassing packaged marketing brands:
                  </Text>
                </View>

                <View style={styles.tableCard}>
                  <View style={[styles.tableHeader, { backgroundColor: theme.backgroundSecondary }]}>
                    <Text style={[styles.thCol, { color: theme.textMuted, flex: 2 }]}>High-Protein Staple</Text>
                    <Text style={[styles.thCol, { color: theme.textMuted, flex: 1.2 }]}>Mandi Wholesale</Text>
                    <Text style={[styles.thCol, { color: theme.textMuted, flex: 1.2 }]}>Supermarket</Text>
                  </View>

                  {[
                    { item: 'Roasted Chana (Sattu)', mandi: '₹105/kg', retail: '₹220/kg', protein: '25g/100g' },
                    { item: 'Soya Chunks (Loose)', mandi: '₹75/kg', retail: '₹165/kg', protein: '52g/100g' },
                    { item: 'Raw Peanuts (Mungfali)', mandi: '₹115/kg', retail: '₹240/kg', protein: '26g/100g' },
                    { item: 'Moong Sabut Dal', mandi: '₹110/kg', retail: '₹185/kg', protein: '24g/100g' },
                    { item: 'Fresh Dairy Paneer', mandi: '₹270/kg', retail: '₹440/kg', protein: '18g/100g' },
                  ].map((row, idx) => (
                    <View key={idx} style={[styles.tableRow, { borderBottomColor: theme.cardBorder }]}>
                      <View style={{ flex: 2 }}>
                        <Text style={[styles.tdItem, { color: theme.textPrimary }]}>{row.item}</Text>
                        <Text style={[styles.tdSub, { color: theme.textMuted }]}>{row.protein} Protein</Text>
                      </View>
                      <Text style={[styles.tdMandi, { color: theme.primary, flex: 1.2 }]}>{row.mandi}</Text>
                      <Text style={[styles.tdRetail, { color: theme.rose, flex: 1.2 }]}>{row.retail}</Text>
                    </View>
                  ))}
                </View>
              </View>
            )}

            {/* 4. MICRONUTRIENT & BIOAVAILABILITY */}
            {perkType === 'perk_micronutrient_boost' && (
              <View style={styles.contentCol}>
                <View style={[styles.heroPerkCard, { backgroundColor: theme.primaryLight, borderColor: theme.primary }]}>
                  <View style={styles.cardHeaderRow}>
                    <Heart size={18} color={theme.primary} />
                    <Text style={[styles.cardHeading, { color: theme.primary }]}>
                      Indian Diet Bioavailability & Anti-Nutrient Hacks
                    </Text>
                  </View>
                  <Text style={[styles.cardBodyText, { color: theme.textPrimary }]}>
                    Simple kitchen adjustments that boost nutrient absorption by up to 300%:
                  </Text>
                </View>

                <View style={styles.stepsList}>
                  <View style={[styles.stepItem, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                    <CheckCircle2 size={20} color={theme.primary} />
                    <View style={{ flex: 1, gap: 2 }}>
                      <Text style={[styles.stepTitle, { color: theme.textPrimary }]}>
                        Squeeze Fresh Lemon on Dal (3x Iron Absorption)
                      </Text>
                      <Text style={[styles.stepSub, { color: theme.textSecondary }]}>
                        Vitamin C converts Non-Heme Ferric iron into bioavailable Ferrous iron, tripling iron uptake from Indian lentils.
                      </Text>
                    </View>
                  </View>

                  <View style={[styles.stepItem, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                    <CheckCircle2 size={20} color={theme.cyan} />
                    <View style={{ flex: 1, gap: 2 }}>
                      <Text style={[styles.stepTitle, { color: theme.textPrimary }]}>
                        8-Hour Dal & Chana Soaking (Destroys Phytates)
                      </Text>
                      <Text style={[styles.stepSub, { color: theme.textSecondary }]}>
                        Soaking legumes in warm water activates phytase enzymes, unlocking bound zinc, magnesium, and reducing flatulence.
                      </Text>
                    </View>
                  </View>

                  <View style={[styles.stepItem, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                    <CheckCircle2 size={20} color={theme.amber} />
                    <View style={{ flex: 1, gap: 2 }}>
                      <Text style={[styles.stepTitle, { color: theme.textPrimary }]}>
                        Pinch of Black Pepper with Turmeric (2000% Curcumin)
                      </Text>
                      <Text style={[styles.stepSub, { color: theme.textSecondary }]}>
                        Piperine inhibits hepatic glucuronidation, amplifying curcumin anti-inflammatory potency for post-workout recovery.
                      </Text>
                    </View>
                  </View>
                </View>
              </View>
            )}

            {/* 5. CLINICAL TRANSFORMATION PDF */}
            {perkType === 'perk_clinical_pdf' && (
              <View style={styles.contentCol}>
                <View style={[styles.heroPerkCard, { backgroundColor: theme.indigoLight, borderColor: theme.indigo }]}>
                  <View style={styles.cardHeaderRow}>
                    <FileText size={18} color={theme.indigo} />
                    <Text style={[styles.cardHeading, { color: theme.indigo }]}>
                      Clinical Nutrition & Biometric Summary
                    </Text>
                  </View>
                  <Text style={[styles.cardBodyText, { color: theme.textPrimary }]}>
                    Prepared for patient/client review with certified ICMR dietary reference guidelines:
                  </Text>
                </View>

                <View style={[styles.clinicalReportCard, { backgroundColor: theme.backgroundSecondary, borderColor: theme.cardBorder }]}>
                  <View style={styles.reportRow}>
                    <Text style={[styles.reportLabel, { color: theme.textMuted }]}>Patient / Member:</Text>
                    <Text style={[styles.reportVal, { color: theme.textPrimary }]}>{user.fullName}</Text>
                  </View>
                  <View style={styles.reportRow}>
                    <Text style={[styles.reportLabel, { color: theme.textMuted }]}>Clinical Goal:</Text>
                    <Text style={[styles.reportVal, { color: theme.textPrimary }]}>{user.goalType.toUpperCase()}</Text>
                  </View>
                  <View style={styles.reportRow}>
                    <Text style={[styles.reportLabel, { color: theme.textMuted }]}>Baseline / Target:</Text>
                    <Text style={[styles.reportVal, { color: theme.textPrimary }]}>{user.weightKg} kg ➔ {user.targetWeightKg} kg</Text>
                  </View>
                  <View style={styles.reportRow}>
                    <Text style={[styles.reportLabel, { color: theme.textMuted }]}>Prescribed Energy:</Text>
                    <Text style={[styles.reportVal, { color: theme.textPrimary }]}>{user.dailyCalorieTarget} kcal/day</Text>
                  </View>
                  <View style={styles.reportRow}>
                    <Text style={[styles.reportLabel, { color: theme.textMuted }]}>Macro Distribution:</Text>
                    <Text style={[styles.reportVal, { color: theme.textPrimary }]}>
                      {user.proteinTargetG}g P • {user.carbsTargetG}g C • {user.fatTargetG}g F
                    </Text>
                  </View>
                </View>

                <TouchableOpacity
                  onPress={handleShareReport}
                  style={[styles.shareReportBtn, { backgroundColor: theme.primary }]}
                  activeOpacity={0.85}
                >
                  <Share2 size={16} color="#FFFFFF" />
                  <Text style={styles.shareReportBtnText}>Share Report with Nutritionist / Doctor</Text>
                </TouchableOpacity>
              </View>
            )}
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    maxHeight: '90%',
    paddingTop: 18,
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  iconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: '900',
  },
  headerSub: {
    fontSize: 11,
    marginTop: 2,
  },
  closeBtn: {
    padding: 6,
  },
  scrollContent: {
    paddingVertical: 16,
    gap: 14,
    paddingBottom: 40,
  },
  contentCol: {
    gap: 14,
  },
  heroPerkCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    gap: 8,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cardHeading: {
    fontSize: 14,
    fontWeight: '900',
  },
  cardBodyText: {
    fontSize: 12,
    lineHeight: 17,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metricCard: {
    width: '48%',
    borderRadius: 14,
    borderWidth: 1,
    padding: 12,
    gap: 4,
  },
  metricLabel: {
    fontSize: 10.5,
    fontWeight: '700',
  },
  metricValue: {
    fontSize: 14,
    fontWeight: '900',
  },
  metricSub: {
    fontSize: 10,
  },
  adviceBox: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    gap: 6,
  },
  adviceTitle: {
    fontSize: 12.5,
    fontWeight: '800',
  },
  adviceDesc: {
    fontSize: 11.5,
    lineHeight: 16,
  },
  stepsList: {
    gap: 10,
  },
  stepItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderRadius: 14,
    borderWidth: 1,
    padding: 12,
    gap: 10,
  },
  stepBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  stepNum: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  stepTitle: {
    fontSize: 12.5,
    fontWeight: '800',
  },
  stepSub: {
    fontSize: 11,
    lineHeight: 15,
  },
  tableCard: {
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  tableHeader: {
    flexDirection: 'row',
    padding: 10,
  },
  thCol: {
    fontSize: 10.5,
    fontWeight: '800',
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderBottomWidth: 1,
  },
  tdItem: {
    fontSize: 12,
    fontWeight: '700',
  },
  tdSub: {
    fontSize: 10,
  },
  tdMandi: {
    fontSize: 12,
    fontWeight: '900',
  },
  tdRetail: {
    fontSize: 12,
    fontWeight: '700',
    textDecorationLine: 'line-through',
  },
  clinicalReportCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    gap: 10,
  },
  reportRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reportLabel: {
    fontSize: 11.5,
  },
  reportVal: {
    fontSize: 12,
    fontWeight: '800',
  },
  shareReportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    borderRadius: 14,
    gap: 8,
    marginTop: 6,
  },
  shareReportBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
});
