import React, { createContext, useContext, useState, useEffect } from 'react';
import { SafeStorage } from '../services/storage';

export type AppLanguage =
  | 'en'
  | 'hi'
  | 'hinglish'
  | 'pa'
  | 'ta'
  | 'te'
  | 'mr'
  | 'gu'
  | 'bn'
  | 'kn'
  | 'ml'
  | 'es'
  | 'fr';

export interface LanguageMeta {
  code: AppLanguage;
  label: string;
  nativeLabel: string;
  flag: string;
  region: string;
}

export const AVAILABLE_LANGUAGES: LanguageMeta[] = [
  { code: 'en', label: 'English (India)', nativeLabel: 'English', flag: '🇮🇳', region: 'India (Default)' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', flag: '🇮🇳', region: 'India' },
  { code: 'hinglish', label: 'Hinglish', nativeLabel: 'हिंग्लिश', flag: '🇮🇳', region: 'Desi Urban / Youth' },
  { code: 'pa', label: 'Punjabi', nativeLabel: 'ਪੰਜਾਬੀ', flag: '🇮🇳', region: 'Punjab / North' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी', flag: '🇮🇳', region: 'Maharashtra' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી', flag: '🇮🇳', region: 'Gujarat' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', flag: '🇮🇳', region: 'Bengal / East' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🇮🇳', region: 'Tamil Nadu / South' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', flag: '🇮🇳', region: 'Andhra & Telangana' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ', flag: '🇮🇳', region: 'Karnataka / South' },
  { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം', flag: '🇮🇳', region: 'Kerala / South' },
  { code: 'es', label: 'Spanish', nativeLabel: 'Español', flag: '🇪🇸', region: 'International' },
  { code: 'fr', label: 'French', nativeLabel: 'Français', flag: '🇫🇷', region: 'International' },
];

export interface FoodItemTranslatable {
  name: string;
  hindiName?: string;
  hinglishName?: string;
  regionalNames?: Partial<Record<AppLanguage, string>>;
}

// Comprehensive UI Translations across 13 languages
const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {
    // Navigation & Headers
    home: 'Home',
    meal_plan: 'Meals',
    workout: 'Workout',
    swaps: 'Smart Swaps',
    analytics: 'Analytics',
    settings: 'Settings',
    profile: 'Profile',
    namaste: 'Namaste',
    guest_mode: 'Guest Mode',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    sign_out: 'Sign Out',
    save_changes: 'Save Changes',
    app_language: 'App Language',
    select_language_desc: 'Select your preferred display language',
    stay_logged_in: 'Stay Logged In',
    verified_member: 'Verified Member',
    cloud_synced: 'Cloud Synced',

    // Dashboard & Cards
    daily_energy_balance: 'DAILY ENERGY BALANCE',
    log_meal: 'Log Meal',
    quick_add: 'Quick Add',
    water_tracker: 'DAILY HYDRATION',
    water_glasses: 'Glasses of Water',
    target: 'Target',
    remaining: 'Remaining',
    consumed: 'Consumed',
    burned: 'Burned',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    katoris: 'Katoris',
    phulkas: 'Rotis / Phulkas',
    desi_ghee: 'Pure Desi Ghee',
    add_to_diary: 'Add to Daily Diary',
    calories_left: '{{count}} kcal left today',
    protein_left: '{{count}}g protein left',
    glasses_remaining: '{{count}} glasses remaining',

    // Diet Chart & Modals
    master_diet_chart: 'Personalized Diet Chart',
    diet_chart_sub: 'Targeted for your Indian kitchen & fitness goal',
    swap_dish: 'Swap Dish',
    view_recipe: 'View Preparation',
    portion: 'Portion',
    cost: 'Est. Cost',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    evening_snack: 'Evening Snack',
    dinner: 'Dinner',
    custom_meal: 'Custom Meal',
    search_food: 'Search Indian Food Database...',
    recent_entries: 'Recent Meal Logs',
    saved_meals: 'Saved Custom Meals',
    save_custom_meal: 'Save as My Meal',
    repeat_meal: 'Repeat Meal',

    // Dietary Preferences
    pure_veg: 'Pure Veg',
    jain: 'Jain',
    eggetarian: 'Eggetarian',
    non_veg: 'Non-Veg',

    // Workouts
    start_workout: 'Start Workout',
    exercises: 'Exercises',
    sets: 'Sets',
    reps: 'Reps',
    rest_sec: 'Rest (sec)',
    bodyweight: 'Bodyweight',
    dumbbells: 'Dumbbells',
    gym: 'Gym',
    resistance_bands: 'Bands',
    fat_loss: 'Fat Loss',
    muscle_gain: 'Muscle Gain',
    recomp: 'Body Recomp',
    pcod_control: 'PCOD / Hormonal Balance',
    workout_completed: 'Workout Completed!',
    total_calories_burned: 'Total Calories Burned',

    // Alerts & Notifications
    hydration_reminder: 'Time to drink a glass of water!',
    meal_reminder: 'Time for your healthy meal!',
    session_restored: 'Welcome back! Your session is active.',
  },

  hi: {
    // Navigation & Headers
    home: 'होम',
    meal_plan: 'भोजन योजना',
    workout: 'कसरत',
    swaps: 'स्मार्ट स्वैप',
    analytics: 'प्रगति चार्ट',
    settings: 'सेटिंग्स',
    profile: 'प्रोफ़ाइल',
    namaste: 'नमस्ते',
    guest_mode: 'अतिथि मोड',
    sign_in: 'साइन इन करें',
    sign_up: 'साइन अप करें',
    sign_out: 'साइन आउट',
    save_changes: 'परिवर्तन सहेजें',
    app_language: 'ऐप की भाषा',
    select_language_desc: 'अपनी पसंदीदा भाषा चुनें',
    stay_logged_in: 'लॉग इन रहें',
    verified_member: 'सत्यापित सदस्य',
    cloud_synced: 'क्लाउड सिंक',

    // Dashboard & Cards
    daily_energy_balance: 'दैनिक कैलोरी व ऊर्जा संतुलन',
    log_meal: 'भोजन जोड़ें',
    quick_add: 'त्वरित जोड़ें',
    water_tracker: 'दैनिक जल संतुलन',
    water_glasses: 'गिलास पानी',
    target: 'लक्ष्य',
    remaining: 'शेष',
    consumed: 'खपत',
    burned: 'जलाई गई',
    calories: 'कैलोरी',
    protein: 'प्रोटीन',
    carbs: 'कार्ब्स',
    fat: 'फैट',
    katoris: 'कटोरी',
    phulkas: 'रोटी / फुल्का',
    desi_ghee: 'देसी घी',
    add_to_diary: 'डायरी में दर्ज करें',
    calories_left: 'आज {{count}} kcal शेष है',
    protein_left: '{{count}}g प्रोटीन शेष',
    glasses_remaining: '{{count}} गिलास बाकी',

    // Diet Chart & Modals
    master_diet_chart: 'व्यक्तिगत आहार चार्ट',
    diet_chart_sub: 'आपकी भारतीय रसोई और फिटनेस लक्ष्य के अनुसार',
    swap_dish: 'व्यंजन बदलें',
    view_recipe: 'बनाने की विधि',
    portion: 'मात्रा',
    cost: 'अनुमानित लागत',
    breakfast: 'नाश्ता',
    lunch: 'दोपहर का भोजन',
    evening_snack: 'शाम का नाश्ता',
    dinner: 'रात का खाना',
    custom_meal: 'कस्टम भोजन',
    search_food: 'भारतीय भोजन खोजें...',
    recent_entries: 'हालिया भोजन रिकॉर्ड',
    saved_meals: 'सहेजे गए भोजन',
    save_custom_meal: 'मेरा भोजन सहेजें',
    repeat_meal: 'दोहराएं',

    // Dietary Preferences
    pure_veg: 'शुद्ध शाकाहारी',
    jain: 'जैन आहार',
    eggetarian: 'एगेटेरियन',
    non_veg: 'मांसाहारी',

    // Workouts
    start_workout: 'कसरत शुरू करें',
    exercises: 'व्यायाम',
    sets: 'सेट्स',
    reps: 'रेप्स',
    rest_sec: 'विश्राम (सेकंड)',
    bodyweight: 'बॉडीवेट',
    dumbbells: 'डम्बल',
    gym: 'जिम',
    resistance_bands: 'रेजिस्टेंस बैंड',
    fat_loss: 'फैट लॉस',
    muscle_gain: 'मसल गेन',
    recomp: 'बॉडी रीकंपोज़िशन',
    pcod_control: 'पीसीओडी / हार्मोन नियंत्रण',
    workout_completed: 'कसरत पूरी हुई!',
    total_calories_burned: 'कुल जलाई गई कैलोरी',

    // Alerts & Notifications
    hydration_reminder: 'एक गिलास पानी पीने का समय!',
    meal_reminder: 'पौष्टिक भोजन का समय हो गया!',
    session_restored: 'वापसी पर स्वागत है! आपका सत्र सक्रिय है।',
  },

  hinglish: {
    // Navigation & Headers
    home: 'Home',
    meal_plan: 'Meal Plan',
    workout: 'Workout',
    swaps: 'Smart Swaps',
    analytics: 'Analytics',
    settings: 'Settings',
    profile: 'Profile',
    namaste: 'Namaste',
    guest_mode: 'Guest Mode',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    sign_out: 'Log Out',
    save_changes: 'Save Changes',
    app_language: 'App Language',
    select_language_desc: 'Apni pasandida bhasha choose karein',
    stay_logged_in: 'Log In Rahein',
    verified_member: 'Verified Member',
    cloud_synced: 'Cloud Synced',

    // Dashboard & Cards
    daily_energy_balance: 'DAILY ENERGY & CALORIES',
    log_meal: 'Meal Log Karein',
    quick_add: 'Quick Add',
    water_tracker: 'DAILY WATER INTAKE',
    water_glasses: 'Glass Paani',
    target: 'Target',
    remaining: 'Remaining',
    consumed: 'Consumed',
    burned: 'Burned',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    katoris: 'Katori',
    phulkas: 'Roti / Phulka',
    desi_ghee: 'Desi Ghee',
    add_to_diary: 'Diary Me Add Karein',
    calories_left: 'Aaj {{count}} kcal bachi hain',
    protein_left: '{{count}}g protein baaki',
    glasses_remaining: '{{count}} glass paani bacha hai',

    // Diet Chart & Modals
    master_diet_chart: 'Personalized Diet Chart',
    diet_chart_sub: 'Apki Indian kitchen aur fitness goal ke hisaab se',
    swap_dish: 'Dish Change Karein',
    view_recipe: 'Recipe Dekhein',
    portion: 'Portion',
    cost: 'Est. Cost',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    evening_snack: 'Evening Snack',
    dinner: 'Dinner',
    custom_meal: 'Custom Meal',
    search_food: 'Indian Food Search Karein...',
    recent_entries: 'Recent Meal Logs',
    saved_meals: 'Saved Meals',
    save_custom_meal: 'Mera Meal Save Karein',
    repeat_meal: 'Repeat Karein',

    // Dietary Preferences
    pure_veg: 'Pure Veg',
    jain: 'Jain Food',
    eggetarian: 'Eggetarian',
    non_veg: 'Non-Veg',

    // Workouts
    start_workout: 'Workout Start Karein',
    exercises: 'Exercises',
    sets: 'Sets',
    reps: 'Reps',
    rest_sec: 'Rest (seconds)',
    bodyweight: 'Bodyweight',
    dumbbells: 'Dumbbells',
    gym: 'Gym',
    resistance_bands: 'Resistance Bands',
    fat_loss: 'Fat Loss',
    muscle_gain: 'Muscle Gain',
    recomp: 'Body Recomp',
    pcod_control: 'PCOD Control',
    workout_completed: 'Workout Khatam!',
    total_calories_burned: 'Total Calories Burned',

    // Alerts & Notifications
    hydration_reminder: 'Paani peene ka time ho gaya!',
    meal_reminder: 'Meal lene ka time ho gaya!',
    session_restored: 'Welcome back! Aap logged in hain.',
  },

  pa: {
    home: 'ਹੋਮ',
    meal_plan: 'ਭੋਜਨ ਯੋਜਨਾ',
    workout: 'ਕਸਰਤ',
    swaps: 'ਸਮਾਰਟ ਸਵੈਪ',
    analytics: 'ਅੰਕੜੇ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    namaste: 'ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ',
    guest_mode: 'ਮਹਿਮਾਨ ਮੋਡ',
    sign_in: 'ਸਾਈਨ ਇਨ',
    sign_up: 'ਸਾਈਨ ਅੱਪ',
    sign_out: 'ਸਾਈਨ ਆਊਟ',
    save_changes: 'ਤਬਦੀਲੀਆਂ ਸੰਭਾਲੋ',
    app_language: 'ਐਪ ਭਾਸ਼ਾ',
    select_language_desc: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ',
    stay_logged_in: 'ਲਾਗ ਇਨ ਰਹੋ',
    verified_member: 'ਪ੍ਰਮਾਣਿਤ ਮੈਂਬਰ',
    cloud_synced: 'ਕਲਾਉਡ ਸਿੰਕ',
    daily_energy_balance: 'ਰੋਜ਼ਾਨਾ ਊਰਜਾ ਸੰਤੁਲਨ',
    log_meal: 'ਭੋਜਨ ਦਰਜ ਕਰੋ',
    quick_add: 'ਤੁਰੰਤ ਸ਼ਾਮਲ ਕਰੋ',
    water_tracker: 'ਰੋਜ਼ਾਨਾ ਪਾਣੀ ਟਰੈਕਰ',
    water_glasses: 'ਗਲਾਸ ਪਾਣੀ',
    target: 'ਟੀਚਾ',
    remaining: 'ਬਾਕੀ',
    consumed: 'ਵਰਤਿਆ',
    burned: 'ਸਾੜਿਆ',
    calories: 'ਕੈਲੋਰੀਆਂ',
    protein: 'ਪ੍ਰੋਟੀਨ',
    carbs: 'ਕਾਰਬਸ',
    fat: 'ਚਰਬੀ',
    katoris: 'ਕਟੋਰੀਆਂ',
    phulkas: 'ਰੋਟੀਆਂ / ਫੁਲਕੇ',
    desi_ghee: 'ਦੇਸੀ ਘਿਓ',
    add_to_diary: 'ਡਾਇਰੀ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
    calories_left: 'ਅੱਜ {{count}} kcal ਬਾਕੀ',
    protein_left: '{{count}}g ਪ੍ਰੋਟੀਨ ਬਾਕੀ',
    glasses_remaining: '{{count}} ਗਲਾਸ ਬਾਕੀ',
    master_diet_chart: 'ਨਿੱਜੀ ਖੁਰਾਕ ਚਾਰਟ',
    diet_chart_sub: 'ਤੁਹਾਡੀ ਰਸੋਈ ਅਤੇ ਤੰਦਰੁਸਤੀ ਟੀਚੇ ਅਨੁਸਾਰ',
    swap_dish: 'ਪਕਵਾਨ ਬਦਲੋ',
    view_recipe: 'ਵਿਧੀ ਦੇਖੋ',
    portion: 'ਹਿੱਸਾ',
    cost: 'ਅਨੁਮਾਨਿਤ ਲਾਗਤ',
    breakfast: 'ਨਾਸ਼ਤਾ',
    lunch: 'ਦੁਪਹਿਰ ਦਾ ਖਾਣਾ',
    evening_snack: 'ਸ਼ਾਮ ਦਾ ਨਾਸ਼ਤਾ',
    dinner: 'ਰਾਤ ਦਾ ਖਾਣਾ',
    custom_meal: 'ਕਸਟਮ ਭੋਜਨ',
    search_food: 'ਖਾਣਾ ਖੋਜੋ...',
    recent_entries: 'ਹਾਲੀਆ ਰਿਕਾਰਡ',
    saved_meals: 'ਸੰਭਾਲਿਆ ਭੋਜਨ',
    save_custom_meal: 'ਭੋਜਨ ਸੰਭਾਲੋ',
    repeat_meal: 'ਦੁਹਰਾਓ',
    pure_veg: 'ਸ਼ੁੱਧ ਸ਼ਾਕਾਹਾਰੀ',
    jain: 'ਜੈਨ ਭੋਜਨ',
    eggetarian: 'ਅੰਡੇ ਵਾਲਾ',
    non_veg: 'ਮਾਸਾਹਾਰੀ',
    start_workout: 'ਕਸਰਤ ਸ਼ੁਰੂ ਕਰੋ',
    exercises: 'ਕਸਰਤਾਂ',
    sets: 'ਸੈੱਟ',
    reps: 'ਰੈਪਸ',
    rest_sec: 'ਅਰਾਮ (ਸਕਿੰਟ)',
    bodyweight: 'ਬਾਡੀਵੇਟ',
    dumbbells: 'ਡੰਬਲ',
    gym: 'ਜਿਮ',
    resistance_bands: 'ਬੈਂਡਸ',
    fat_loss: 'ਚਰਬੀ ਘਟਾਓ',
    muscle_gain: 'ਮਾਸਪੇਸ਼ੀਆਂ ਵਧਾਓ',
    recomp: 'ਬਾਡੀ ਰੀਕੰਪ',
    pcod_control: 'ਪੀਸੀਓਡੀ ਕੰਟਰੋਲ',
    workout_completed: 'ਕਸਰਤ ਪੂਰੀ ਹੋਈ!',
    total_calories_burned: 'ਕੁੱਲ ਸਾੜੀਆਂ ਕੈਲੋਰੀਆਂ',
    hydration_reminder: 'ਪਾਣੀ ਪੀਣ ਦਾ ਸਮਾਂ!',
    meal_reminder: 'ਖਾਣ ਦਾ ਸਮਾਂ ਹੋ ਗਿਆ!',
    session_restored: 'ਜੀ ਆਇਆਂ ਨੂੰ! ਸੈਸ਼ਨ ਸਰਗਰਮ ਹੈ।',
  },

  mr: {
    home: 'मुख्यपृष्ठ',
    meal_plan: 'आहार योजना',
    workout: 'व्यायाम',
    swaps: 'स्मार्ट पर्याय',
    analytics: 'प्रगती विश्लेषण',
    settings: 'सेटिंग्ज',
    profile: 'प्रोफाइल',
    namaste: 'नमस्ते',
    guest_mode: 'अतिथी मोड',
    sign_in: 'साइन इन',
    sign_up: 'साइन अप',
    sign_out: 'साइन आउट',
    save_changes: 'बदल जतन करा',
    app_language: 'अ‍ॅप भाषा',
    select_language_desc: 'आपली पसंतीची भाषा निवडा',
    stay_logged_in: 'लॉग इन राहा',
    verified_member: 'सत्यापित सदस्य',
    cloud_synced: 'क्लाउड सिंक',
    daily_energy_balance: 'दैनिक ऊर्जा संतुलन',
    log_meal: 'जेवण नोंदवा',
    quick_add: 'त्वरित जोडा',
    water_tracker: 'दैनिक पाणी ट्रॅकर',
    water_glasses: 'ग्लास पाणी',
    target: 'ध्येय',
    remaining: 'शिल्लक',
    consumed: 'वापरलेले',
    burned: 'जाळलेले',
    calories: 'कॅलरीज',
    protein: 'प्रोटीन',
    carbs: 'कार्ब्स',
    fat: 'फॅट',
    katoris: 'वाट्या',
    phulkas: 'चपाती / फुलके',
    desi_ghee: 'शुद्ध साजूक तूप',
    add_to_diary: 'डायरीत नोंदवा',
    calories_left: 'आज {{count}} kcal शिल्लक',
    protein_left: '{{count}}g प्रोटीन शिल्लक',
    glasses_remaining: '{{count}} ग्लास पाणी बाकी',
    master_diet_chart: 'वैयक्तिक आहार चार्ट',
    diet_chart_sub: 'तुमच्या स्वयंपाकघरासाठी आणि आरोग्यासाठी',
    swap_dish: 'पदार्थ बदला',
    view_recipe: 'कृती पहा',
    portion: 'प्रमाण',
    cost: 'अंदाजे खर्च',
    breakfast: 'न्याहारी',
    lunch: 'दुपारचे जेवण',
    evening_snack: 'संध्याकाळचा नाश्ता',
    dinner: 'रात्रीचे जेवण',
    custom_meal: 'कस्टम आहार',
    search_food: 'अन्न शोधा...',
    recent_entries: 'अलीकडील नोंदी',
    saved_meals: 'जतन केलेले जेवण',
    save_custom_meal: 'जेवण जतन करा',
    repeat_meal: 'पुन्हा जोडा',
    pure_veg: 'शाकाहारी',
    jain: 'जैन आहार',
    eggetarian: 'अंडेयुक्त',
    non_veg: 'मांसाहारी',
    start_workout: 'व्यायाम सुरू करा',
    exercises: 'व्यायाम प्रकार',
    sets: 'सेट्स',
    reps: 'रेप्स',
    rest_sec: 'विश्रांती (सेकंद)',
    bodyweight: 'बॉडीवेट',
    dumbbells: 'डंबेल',
    gym: 'जिम',
    resistance_bands: 'रेझिस्टन्स बँड',
    fat_loss: 'चरबी कमी करा',
    muscle_gain: 'स्नायू वाढवा',
    recomp: 'शरीर पुनर्रचना',
    pcod_control: 'पीसीओडी नियंत्रण',
    workout_completed: 'व्यायाम पूर्ण झाला!',
    total_calories_burned: 'एकूण जळलेल्या कॅलरीज',
    hydration_reminder: 'पाणी पिण्याची वेळ झाली!',
    meal_reminder: 'जेवणाची वेळ झाली!',
    session_restored: 'स्वागत आहे! तुमचे सत्र सक्रिय आहे.',
  },

  gu: {
    home: 'હોમ',
    meal_plan: 'આહાર યોજના',
    workout: 'કસરત',
    swaps: 'સ્માર્ટ સ્વેપ',
    analytics: 'પ્રગતિ વિશ્લેષણ',
    settings: 'સેટિંગ્સ',
    profile: 'પ્રોફાઇલ',
    namaste: 'નમસ્તે',
    guest_mode: 'ગેસ્ટ મોડ',
    sign_in: 'સાઇન ઇન',
    sign_up: 'સાઇન અપ',
    sign_out: 'સાઇન આઉટ',
    save_changes: 'ફેરફારો સાચવો',
    app_language: 'એપ ભાષા',
    select_language_desc: 'તમારી પસંદગીની ભાષા પસંદ કરો',
    stay_logged_in: 'લૉગ ઇન રહો',
    verified_member: 'ચકાસાયેલ સભ્ય',
    cloud_synced: 'ક્લાઉડ સિંક',
    daily_energy_balance: 'દૈનિક ઊર્જા સંતુલન',
    log_meal: 'ખોરાક ઉમેરો',
    quick_add: 'ઝડપી ઉમેરો',
    water_tracker: 'દૈનિક પાણી ટ્રેકર',
    water_glasses: 'ગ્લાસ પાણી',
    target: 'ધ્યેય',
    remaining: 'બાકી',
    consumed: 'વપરાયેલ',
    burned: 'બાળેલ',
    calories: 'કેલરી',
    protein: 'પ્રોટીન',
    carbs: 'કાર્બ્સ',
    fat: 'ચરબી',
    katoris: 'વાટકી',
    phulkas: 'રોટલી / ફુલકા',
    desi_ghee: 'શુદ્ધ દેશી ઘી',
    add_to_diary: 'ડાયરીમાં ઉમેરો',
    calories_left: 'આજે {{count}} kcal બાકી છે',
    protein_left: '{{count}}g પ્રોટીન બાકી',
    glasses_remaining: '{{count}} ગ્લાસ બાકી',
    master_diet_chart: 'વ્યક્તિગત ડાયેટ ચાર્ટ',
    diet_chart_sub: 'તમારા રસોડા અને ફિટનેસ લક્ષ્ય માટે',
    swap_dish: 'વાનગી બદલો',
    view_recipe: 'બનાવવાની રીત',
    portion: 'માપ',
    cost: 'અંદાજિત ખર્ચ',
    breakfast: 'સવારનો નાસ્તો',
    lunch: 'બપોરનું ભોજન',
    evening_snack: 'સાંજનો નાસ્તો',
    dinner: 'રાતનું ભોજન',
    custom_meal: 'કસ્ટમ ભોજન',
    search_food: 'ખોરાક શોધો...',
    recent_entries: 'તાજેતરની યાદી',
    saved_meals: 'સાચવેલ ભોજન',
    save_custom_meal: 'ભોજન સાચવો',
    repeat_meal: 'ફરીથી લો',
    pure_veg: 'શુદ્ધ શાકાહારી',
    jain: 'જૈન ભોજન',
    eggetarian: 'ઈંડા સાથે',
    non_veg: 'માંસાહારી',
    start_workout: 'કસરત શરૂ કરો',
    exercises: 'કસરતો',
    sets: 'સેટ્સ',
    reps: 'રેપ્સ',
    rest_sec: 'વિરામ (સેકન્ડ)',
    bodyweight: 'બોડીવેઇટ',
    dumbbells: 'ડમ્બેલ્સ',
    gym: 'જીમ',
    resistance_bands: 'બેન્ડ્સ',
    fat_loss: 'ફેટ લોસ',
    muscle_gain: 'મસલ ગેઇન',
    recomp: 'બોડી રીકોમ્પ',
    pcod_control: 'પીસીઓડી કંટ્રોલ',
    workout_completed: 'કસરત પૂર્ણ થઈ!',
    total_calories_burned: 'કુલ બળી ગયેલ કેલરી',
    hydration_reminder: 'પાણી પીવાનો સમય થયો!',
    meal_reminder: 'ભોજન કરવાનો સમય થયો!',
    session_restored: 'સ્વાગત છે! તમારું સત્ર સક્રિય છે.',
  },

  bn: {
    home: 'হোম',
    meal_plan: 'খাবার পরিকল্পনা',
    workout: 'ব্যায়াম',
    swaps: 'স্মার্ট অদলবদল',
    analytics: 'বিশ্লেষণ',
    settings: 'সেটিংস',
    profile: 'প্রোফাইল',
    namaste: 'নমস্কার',
    guest_mode: 'গেস্ট মোড',
    sign_in: 'সাইন ইন',
    sign_up: 'সাইন আপ',
    sign_out: 'সাইন আউট',
    save_changes: 'সংরক্ষণ করুন',
    app_language: 'অ্যাপের ভাষা',
    select_language_desc: 'পছন্দের ভাষা নির্বাচন করুন',
    stay_logged_in: 'লগ ইন থাকুন',
    verified_member: 'যাচাইকৃত সদস্য',
    cloud_synced: 'ক্লাউড সিঙ্ক',
    daily_energy_balance: 'দৈনিক শক্তি ভারসাম্য',
    log_meal: 'খাবার যোগ করুন',
    quick_add: 'দ্রুত যোগ',
    water_tracker: 'জল ট্র্যাকার',
    water_glasses: 'গ্লাস জল',
    target: 'লক্ষ্য',
    remaining: 'বাকি',
    consumed: 'গৃহীত',
    burned: 'পোড়ানো',
    calories: 'ক্যালোরি',
    protein: 'প্রোটিন',
    carbs: 'কার্বস',
    fat: 'চর্বি',
    katoris: 'বাটি',
    phulkas: 'রুটি / ফুলকা',
    desi_ghee: 'দেশি ঘি',
    add_to_diary: 'ডায়েরিতে যোগ করুন',
    calories_left: 'আজ {{count}} kcal বাকি',
    protein_left: '{{count}}g প্রোটিন বাকি',
    glasses_remaining: '{{count}} গ্লাস জল বাকি',
    master_diet_chart: 'ব্যক্তিগত ডায়েট চার্ট',
    diet_chart_sub: 'আপনার রান্নাঘর ও লক্ষ্যের উপযোগী',
    swap_dish: 'খাবার পরিবর্তন',
    view_recipe: 'প্রণালী দেখুন',
    portion: 'পরিমাণ',
    cost: 'আনুমানিক খরচ',
    breakfast: 'সকালের নাস্তা',
    lunch: 'দুপুরের খাবার',
    evening_snack: 'সন্ধ্যার নাস্তা',
    dinner: 'রাতের খাবার',
    custom_meal: 'কাস্টম খাবার',
    search_food: 'খাবার খুঁজুন...',
    recent_entries: 'সাম্প্রতিক লগ',
    saved_meals: 'সংরক্ষিত খাবার',
    save_custom_meal: 'সংরক্ষণ করুন',
    repeat_meal: 'পুনরাবৃত্তি করুন',
    pure_veg: 'নিরামিষ',
    jain: 'জৈন খাবার',
    eggetarian: 'ডিমভোজী',
    non_veg: 'আমিষ',
    start_workout: 'ব্যায়াম শুরু করুন',
    exercises: 'ব্যায়ামসমূহ',
    sets: 'সেটস',
    reps: 'রেপস',
    rest_sec: 'বিশ্রাম (সেকেন্ড)',
    bodyweight: 'বডিওয়েট',
    dumbbells: 'ডাম্বেল',
    gym: 'জিম',
    resistance_bands: 'ব্যান্ডস',
    fat_loss: 'ফ্যাট কমানো',
    muscle_gain: 'পেশী গঠন',
    recomp: 'বডি রিকম্প',
    pcod_control: 'পিসিওডি নিয়ন্ত্রণ',
    workout_completed: 'ব্যায়াম সমাপ্ত!',
    total_calories_burned: 'মোট পোড়ানো ক্যালোরি',
    hydration_reminder: 'জল পানের সময় হয়েছে!',
    meal_reminder: 'খাবারের সময় হয়েছে!',
    session_restored: 'স্বাগতম! আপনার সেশন সক্রিয়।',
  },

  ta: {
    home: 'முகப்பு',
    meal_plan: 'உணவு திட்டம்',
    workout: 'உடற்பயிற்சி',
    swaps: 'ஸ்மார்ட் மாற்று',
    analytics: 'முன்னேற்றம்',
    settings: 'அமைப்புகள்',
    profile: 'சுயவிவரம்',
    namaste: 'வணக்கம்',
    guest_mode: 'விருந்தினர் பயன்முறை',
    sign_in: 'உள்நுழைக',
    sign_up: 'பதிவு செய்க',
    sign_out: 'வெளியேறுக',
    save_changes: 'சேமிக்கவும்',
    app_language: 'செயலி மொழி',
    select_language_desc: 'விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
    stay_logged_in: 'உள்நுழைந்தே இருங்கள்',
    verified_member: 'உறுதிப்படுத்தப்பட்ட உறுப்பினர்',
    cloud_synced: 'கிளவுட் ஒத்திசைவு',
    daily_energy_balance: 'தினசரி ஆற்றல் சமநிலை',
    log_meal: 'உணவை சேர்க்க',
    quick_add: 'விரைவாக சேர்',
    water_tracker: 'நீர் கண்காணிப்பு',
    water_glasses: 'டம்ளர் தண்ணீர்',
    target: 'இலக்கு',
    remaining: 'மீதம்',
    consumed: 'உட்கொண்டது',
    burned: 'எரித்தது',
    calories: 'கலோரிகள்',
    protein: 'புரதம்',
    carbs: 'கார்போஹைட்ரேட்',
    fat: 'கொழுப்பு',
    katoris: 'கிண்ணங்கள்',
    phulkas: 'சப்பாத்தி / ரொட்டி',
    desi_ghee: 'சுத்தமான நெய்',
    add_to_diary: 'குறிப்பேட்டில் சேர்க்க',
    calories_left: 'இன்று {{count}} kcal மீதம்',
    protein_left: '{{count}}g புரதம் மீதம்',
    glasses_remaining: '{{count}} டம்ளர்கள் மீதம்',
    master_diet_chart: 'தனிப்பயன் உணவு அட்டவணை',
    diet_chart_sub: 'உங்கள் சமையலறை மற்றும் உடற்பயிற்சி இலக்குக்கு ஏற்ப',
    swap_dish: 'உணவை மாற்றுக',
    view_recipe: 'செய்முறை காண்க',
    portion: 'அளவு',
    cost: 'மதிப்பிடப்பட்ட செலவு',
    breakfast: 'காலை உணவு',
    lunch: 'மதிய உணவு',
    evening_snack: 'மாலை சிற்றுண்டி',
    dinner: 'இரவு உணவு',
    custom_meal: 'விருப்ப உணவு',
    search_food: 'உணவை தேடுக...',
    recent_entries: 'சமீபத்திய பதிவுகள்',
    saved_meals: 'சேமித்த உணவுகள்',
    save_custom_meal: 'உணவை சேமி',
    repeat_meal: 'மீண்டும் சேர்',
    pure_veg: 'சைவம்',
    jain: 'ஜெயின் உணவு',
    eggetarian: 'முட்டை சைவம்',
    non_veg: 'அசைவம்',
    start_workout: 'உடற்பயிற்சி தொடங்குக',
    exercises: 'பயிற்சிகள்',
    sets: 'செட்கள்',
    reps: 'முறைகள்',
    rest_sec: 'ஓய்வு (வினாடிகள்)',
    bodyweight: 'உடல் எடை பயிற்சி',
    dumbbells: 'டம்பெல்ஸ்',
    gym: 'ஜிம்',
    resistance_bands: 'ரெசிஸ்டன்ஸ் பேண்ட்ஸ்',
    fat_loss: 'கொழுப்பு குறைப்பு',
    muscle_gain: 'தசை பெருக்கம்',
    recomp: 'உடல் மறுசீரமைப்பு',
    pcod_control: 'பிசிஓடி கட்டுப்பாடு',
    workout_completed: 'பயிற்சி முடிந்தது!',
    total_calories_burned: 'மொத்த எரித்த கலோரிகள்',
    hydration_reminder: 'தண்ணீர் குடிக்கும் நேரம்!',
    meal_reminder: 'உணவு உண்ணும் நேரம்!',
    session_restored: 'நல்வரவு! அமர்வு செயலில் உள்ளது.',
  },

  te: {
    home: 'హోమ్',
    meal_plan: 'భోజన ప్రణాళిక',
    workout: 'వ్యాయామం',
    swaps: 'స్మార్ట్ మార్పులు',
    analytics: 'విశ్లేషణ',
    settings: 'సెట్టింగ్‌లు',
    profile: 'ప్రొఫైల్',
    namaste: 'నమస్కారం',
    guest_mode: 'గెస్ట్ మోడ్',
    sign_in: 'సైన్ ఇన్',
    sign_up: 'సైన్ అప్',
    sign_out: 'సైన్ అవుట్',
    save_changes: 'మార్పులను సేవ్ చేయండి',
    app_language: 'యాప్ భాష',
    select_language_desc: 'మీకు నచ్చిన భాషను ఎంచుకోండి',
    stay_logged_in: 'లాగిన్ అయి ఉండండి',
    verified_member: 'ధృవీకరించబడిన సభ్యుడు',
    cloud_synced: 'క్లౌడ్ సింక్',
    daily_energy_balance: 'రోజువారీ శక్తి సమతుల్యత',
    log_meal: 'భోజనం నమోదు చేయండి',
    quick_add: 'త్వరిత జోడింపు',
    water_tracker: 'నీటి ట్రాకర్',
    water_glasses: 'గ్లాసుల నీరు',
    target: 'లక్ష్యం',
    remaining: 'మిగిలినవి',
    consumed: 'తీసుకున్నవి',
    burned: 'బర్న్ చేసినవి',
    calories: 'క్యాలరీలు',
    protein: 'ప్రోటీన్',
    carbs: 'కార్బ్స్',
    fat: 'కొవ్వు',
    katoris: 'గిన్నెలు',
    phulkas: 'రోటీలు / పుల్కాలు',
    desi_ghee: 'స్వచ్ఛమైన నెయ్యి',
    add_to_diary: 'డైరీలో జోడించండి',
    calories_left: 'ఈరోజు {{count}} kcal మిగిలి ఉన్నాయి',
    protein_left: '{{count}}g ప్రోటీన్ మిగిలి ఉంది',
    glasses_remaining: '{{count}} గ్లాసులు మిగిలాయి',
    master_diet_chart: 'వ్యక్తిగత డైట్ చార్ట్',
    diet_chart_sub: 'మీ వంటగది మరియు లక్ష్యానికి అనుగుణంగా',
    swap_dish: 'వంటకాన్ని మార్చండి',
    view_recipe: 'రెసిపీ చూడండి',
    portion: 'పరిమాణం',
    cost: 'అంచనా వ్యయం',
    breakfast: 'అల్పాహారం',
    lunch: 'మధ్యాహ్న భోజనం',
    evening_snack: 'సాయంత్రం స్నాక్',
    dinner: 'రాత్రి భోజనం',
    custom_meal: 'కస్టమ్ భోజనం',
    search_food: 'ఆహారాన్ని వెతకండి...',
    recent_entries: 'ఇటీవలి లాగ్‌లు',
    saved_meals: 'సేవ్ చేసిన భోజనాలు',
    save_custom_meal: 'భోజనాన్ని సేవ్ చేయండి',
    repeat_meal: 'మళ్లీ జోడించండి',
    pure_veg: 'శాకాహారం',
    jain: 'జైన్ ఆహారం',
    eggetarian: 'ఎగ్గేటేరియన్',
    non_veg: 'మాంసాహారం',
    start_workout: 'వ్యాయామం ప్రారంభించండి',
    exercises: 'వ్యాయామాలు',
    sets: 'సెట్లు',
    reps: 'రెప్స్',
    rest_sec: 'విశ్రాంతి (సెకన్లు)',
    bodyweight: 'బాడీవెయిట్',
    dumbbells: 'డంబెల్స్',
    gym: 'జిమ్',
    resistance_bands: 'రెసిస్టెన్స్ బ్యాండ్స్',
    fat_loss: 'ఫ్యాట్ లాస్',
    muscle_gain: 'కండరాల పెరుగుదల',
    recomp: 'బాడీ రీకాంపోజిషన్',
    pcod_control: 'పిసిఓడి నియంత్రణ',
    workout_completed: 'వ్యాయామం పూర్తయింది!',
    total_calories_burned: 'మొత్తం బర్న్ చేసిన క్యాలరీలు',
    hydration_reminder: 'నీరు త్రాగే సమయం అయింది!',
    meal_reminder: 'భోజనం చేసే సమయం అయింది!',
    session_restored: 'స్వాగతం! మీ సెషన్ సక్రియంగా ఉంది.',
  },

  kn: {
    home: 'ಮುಖಪುಟ',
    meal_plan: 'ಆಹಾರ ಯೋಜನೆ',
    workout: 'ವ್ಯಾಯಾಮ',
    swaps: 'ಸ್ಮಾರ್ಟ್ ಬದಲಾವಣೆ',
    analytics: 'ಪ್ರಗತಿ ವಿಶ್ಲೇಷಣೆ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    namaste: 'ನಮಸ್ಕಾರ',
    guest_mode: 'ಅತಿಥಿ ಮೋಡ್',
    sign_in: 'ಸೈನ್ ಇನ್',
    sign_up: 'ಸೈನ್ ಅಪ್',
    sign_out: 'ಸೈನ್ ಔಟ್',
    save_changes: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    app_language: 'ಆ್ಯಪ್ ಭಾಷೆ',
    select_language_desc: 'ನಿಮ್ಮ ಮೆಚ್ಚಿನ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    stay_logged_in: 'ಲಾಗ್ ಇನ್ ಆಗಿರಿ',
    verified_member: 'ದೃಢೀಕೃತ ಸದಸ್ಯ',
    cloud_synced: 'ಕ್ಲೌಡ್ ಸಿಂಕ್',
    daily_energy_balance: 'ದೈನಂದಿನ ಶಕ್ತಿ ಸಮತೋಲನ',
    log_meal: 'ಆಹಾರ ಸೇರಿಸಿ',
    quick_add: 'ತ್ವರಿತ ಸೇರ್ಪಡೆ',
    water_tracker: 'ನೀರಿನ ಟ್ರ್ಯಾಕರ್',
    water_glasses: 'ಗ್ಲಾಸ್ ನೀರು',
    target: 'ಗುರಿ',
    remaining: 'ಉಳಿದಿದೆ',
    consumed: 'ಸೇವಿಸಿದ್ದು',
    burned: 'ದಹಿಸಿದ್ದು',
    calories: 'ಕ್ಯಾಲೋರಿಗಳು',
    protein: 'ಪ್ರೋಟೀನ್',
    carbs: 'ಕಾರ್ಬ್ಸ್',
    fat: 'ಕೊಬ್ಬು',
    katoris: 'ಬಟ್ಟಲುಗಳು',
    phulkas: 'ರೊಟ್ಟಿ / ಚಪಾತಿ',
    desi_ghee: 'ಶುದ್ಧ ತುಪ್ಪ',
    add_to_diary: 'ಡೈರಿಗೆ ಸೇರಿಸಿ',
    calories_left: 'ಇಂದು {{count}} kcal ಉಳಿದಿದೆ',
    protein_left: '{{count}}g ಪ್ರೋಟೀನ್ ಉಳಿದಿದೆ',
    glasses_remaining: '{{count}} ಗ್ಲಾಸ್‌ಗಳು ಉಳಿದಿವೆ',
    master_diet_chart: 'ವೈಯಕ್ತಿಕ ಆಹಾರ ಚಾರ್ಟ್',
    diet_chart_sub: 'ನಿಮ್ಮ ಅಡುಗೆಮನೆ ಮತ್ತು ಫಿಟ್‌ನೆಸ್ ಗುರಿಗೆ ಸೂಕ್ತ',
    swap_dish: 'ಖಾದ್ಯ ಬದಲಾಯಿಸಿ',
    view_recipe: 'ಮಾಡುವ ವಿಧಾನ',
    portion: 'ಪ್ರಮಾಣ',
    cost: 'ಅಂದಾಜು ವೆಚ್ಚ',
    breakfast: 'ಉಪಾಹಾರ',
    lunch: 'ಮಧ್ಯಾಹ್ನದ ಊಟ',
    evening_snack: 'ಸಂಜೆಯ ಉಪಾಹಾರ',
    dinner: 'ರಾತ್ರಿಯ ಊಟ',
    custom_meal: 'ಕಸ್ಟಮ್ ಆಹಾರ',
    search_food: 'ಆಹಾರ ಹುಡುಕಿ...',
    recent_entries: 'ಇತ್ತೀಚಿನ ದಾಖಲೆಗಳು',
    saved_meals: 'ಉಳಿಸಿದ ಆಹಾರಗಳು',
    save_custom_meal: 'ಆಹಾರ ಉಳಿಸಿ',
    repeat_meal: 'ಪುನರಾವರ್ತಿಸಿ',
    pure_veg: 'ಸಸ್ಯಾಹಾರಿ',
    jain: 'ಜೈನ ಆಹಾರ',
    eggetarian: 'ಮೊಟ್ಟೆಯುಕ್ತ',
    non_veg: 'ಮಾಂಸಾಹಾರಿ',
    start_workout: 'ವ್ಯಾಯಾಮ ಪ್ರಾರಂಭಿಸಿ',
    exercises: 'ವ್ಯಾಯಾಮಗಳು',
    sets: 'ಸೆಟ್‌ಗಳು',
    reps: 'ರೆಪ್ಸ್',
    rest_sec: 'ವಿಶ್ರಾಂತಿ (ಸೆಕೆಂಡು)',
    bodyweight: 'ಬಾಡಿವೈಟ್',
    dumbbells: 'ಡಂಬೆಲ್ಸ್',
    gym: 'ಜಿಮ್',
    resistance_bands: 'ರೆಸಿಸ್ಟೆನ್ಸ್ ಬ್ಯಾಂಡ್‌ಗಳು',
    fat_loss: 'ಕೊಬ್ಬು ಕರಗಿಸುವಿಕೆ',
    muscle_gain: 'ಸ್ನಾಯು ಬೆಳವಣಿಗೆ',
    recomp: 'ದೇಹ ಮರುರಚನೆ',
    pcod_control: 'ಪಿಸಿಓಡಿ ನಿಯಂತ್ರಣ',
    workout_completed: 'ವ್ಯಾಯಾಮ ಪೂರ್ಣಗೊಂಡಿದೆ!',
    total_calories_burned: 'ಒಟ್ಟು ದಹಿಸಿದ ಕ್ಯಾಲೋರಿಗಳು',
    hydration_reminder: 'ನೀರು ಕುಡಿಯುವ ಸಮಯ!',
    meal_reminder: 'ಊಟ ಮಾಡುವ ಸಮಯ!',
    session_restored: 'ಸುಸ್ವಾಗತ! ನಿಮ್ಮ ಸೆಷನ್ ಸಕ್ರಿಯವಾಗಿದೆ.',
  },

  ml: {
    home: 'ഹോം',
    meal_plan: 'ഭക്ഷണ ക്രമം',
    workout: 'വ്യായാമം',
    swaps: 'സ്മാർട്ട് മാറ്റങ്ങൾ',
    analytics: 'പുരോഗതി',
    settings: 'ക്രമീകരണങ്ങൾ',
    profile: 'പ്രൊഫൈൽ',
    namaste: 'നമസ്കാരം',
    guest_mode: 'ഗസ്റ്റ് മോഡ്',
    sign_in: 'സൈൻ ഇൻ',
    sign_up: 'സൈൻ അപ്പ്',
    sign_out: 'സൈൻ ഔട്ട്',
    save_changes: 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
    app_language: 'ആപ്പ് ഭാഷ',
    select_language_desc: 'നിങ്ങളുടെ ഇഷ്ടപ്പെട്ട ഭാഷ തിരഞ്ഞെടുക്കുക',
    stay_logged_in: 'ലോഗിൻ ആയി തുടരുക',
    verified_member: 'സ്ഥിരീകരിച്ച അംഗം',
    cloud_synced: 'ക്ലൗഡ് സിങ്ക്',
    daily_energy_balance: 'പ്രതിദിന ഊർജ്ജ തുലനാവസ്ഥ',
    log_meal: 'ഭക്ഷണം ചേർക്കുക',
    quick_add: 'പെട്ടെന്ന് ചേർക്കുക',
    water_tracker: 'വെള്ളം കുടിക്കൽ ട്രാക്കർ',
    water_glasses: 'ഗ്ലാസ് വെള്ളം',
    target: 'ലക്ഷ്യം',
    remaining: 'ബാക്കി',
    consumed: 'കഴിച്ചത്',
    burned: 'എരിച്ചത്',
    calories: 'കലോറി',
    protein: 'പ്രോട്ടീൻ',
    carbs: 'കാർബ്സ്',
    fat: 'കൊഴുപ്പ്',
    katoris: 'പാത്രങ്ങൾ',
    phulkas: 'ചപ്പാത്തി / റൊട്ടി',
    desi_ghee: 'ശുദ്ധമായ നെയ്യ്',
    add_to_diary: 'ഡയറിയിൽ ചേർക്കുക',
    calories_left: 'ഇന്ന് {{count}} kcal ബാക്കിയുണ്ട്',
    protein_left: '{{count}}g പ്രോട്ടീൻ ബാക്കി',
    glasses_remaining: '{{count}} ഗ്ലാസുകൾ ബാക്കി',
    master_diet_chart: 'വ്യക്തിഗത ഡയറ്റ് ചാർട്ട്',
    diet_chart_sub: 'നിങ്ങളുടെ അടുക്കളയ്ക്കും ലക്ഷ്യത്തിനും അനുയോജ്യം',
    swap_dish: 'വിഭവം മാറ്റുക',
    view_recipe: 'പാചകക്കുറിപ്പ് കാണുക',
    portion: 'അളവ്',
    cost: 'കണക്കാക്കിയ ചിലവ്',
    breakfast: 'പ്രഭാതഭക്ഷണം',
    lunch: 'ഉച്ചഭക്ഷണം',
    evening_snack: 'വൈകുന്നേരത്തെ ലഘുഭക്ഷണം',
    dinner: 'അത്താഴം',
    custom_meal: 'കസ്റ്റം ഭക്ഷണം',
    search_food: 'ഭക്ഷണം തിരയുക...',
    recent_entries: 'സമീപകാല ലോഗുകൾ',
    saved_meals: 'സേവ് ചെയ്ത ഭക്ഷണങ്ങൾ',
    save_custom_meal: 'ഭക്ഷണം സേവ് ചെയ്യുക',
    repeat_meal: 'വീണ്ടും ചേർക്കുക',
    pure_veg: 'സസ്യാഹാരം',
    jain: 'ജൈന ഭക്ഷണം',
    eggetarian: 'മുട്ട ഉൾപ്പെട്ടത്',
    non_veg: 'മാംസാഹാരം',
    start_workout: 'വ്യായാമം ആരംഭിക്കുക',
    exercises: 'വ്യായാമങ്ങൾ',
    sets: 'സെറ്റുകൾ',
    reps: 'റെപ്സ്',
    rest_sec: 'വിശ്രമം (സെക്കൻഡ്)',
    bodyweight: 'ബോഡിവെയ്റ്റ്',
    dumbbells: 'ഡംബെൽസ്',
    gym: 'ജിം',
    resistance_bands: 'ബാൻഡുകൾ',
    fat_loss: 'കൊഴുപ്പ് കുറയ്ക്കൽ',
    muscle_gain: 'പേശി വളർത്തൽ',
    recomp: 'ബോഡി റീകോമ്പോസിഷൻ',
    pcod_control: 'പിസിഒഡി നിയന്ത്രണം',
    workout_completed: 'വ്യായാമം പൂർത്തിയായി!',
    total_calories_burned: 'ആകെ എരിച്ച കലോറികൾ',
    hydration_reminder: 'വെള്ളം കുടിക്കാനുള്ള സമയം!',
    meal_reminder: 'ഭക്ഷണം കഴിക്കാനുള്ള സമയം!',
    session_restored: 'സ്വാഗതം! സെഷൻ സജീവമാണ്.',
  },

  es: {
    home: 'Inicio',
    meal_plan: 'Comidas',
    workout: 'Entrenamiento',
    swaps: 'Sustitutos',
    analytics: 'Progreso',
    settings: 'Ajustes',
    profile: 'Perfil',
    namaste: 'Hola',
    guest_mode: 'Modo Invitado',
    sign_in: 'Iniciar Sesión',
    sign_up: 'Registrarse',
    sign_out: 'Cerrar Sesión',
    save_changes: 'Guardar Cambios',
    app_language: 'Idioma de la App',
    select_language_desc: 'Seleccione su idioma preferido',
    stay_logged_in: 'Mantener Sesión',
    verified_member: 'Miembro Verificado',
    cloud_synced: 'Sincronizado en la Nube',
    daily_energy_balance: 'BALANCE ENERGÉTICO DIARIO',
    log_meal: 'Registrar Comida',
    quick_add: 'Añadir Rápido',
    water_tracker: 'HIDRATACIÓN DIARIA',
    water_glasses: 'Vasos de Agua',
    target: 'Objetivo',
    remaining: 'Restante',
    consumed: 'Consumido',
    burned: 'Quemado',
    calories: 'Calorías',
    protein: 'Proteína',
    carbs: 'Carbohidratos',
    fat: 'Grasa',
    katoris: 'Porciones',
    phulkas: 'Panes / Rotis',
    desi_ghee: 'Ghee Puro',
    add_to_diary: 'Añadir al Diario',
    calories_left: 'Quedan {{count}} kcal hoy',
    protein_left: 'Quedan {{count}}g de proteína',
    glasses_remaining: 'Quedan {{count}} vasos',
    master_diet_chart: 'Plan de Dieta Personalizado',
    diet_chart_sub: 'Adaptado a su cocina y objetivos de fitness',
    swap_dish: 'Cambiar Plato',
    view_recipe: 'Ver Receta',
    portion: 'Porción',
    cost: 'Coste Estimado',
    breakfast: 'Desayuno',
    lunch: 'Almuerzo',
    evening_snack: 'Merienda',
    dinner: 'Cena',
    custom_meal: 'Comida Personalizada',
    search_food: 'Buscar Comida...',
    recent_entries: 'Registros Recientes',
    saved_meals: 'Comidas Guardadas',
    save_custom_meal: 'Guardar Comida',
    repeat_meal: 'Repetir',
    pure_veg: 'Vegetariano Puro',
    jain: 'Dieta Jainista',
    eggetarian: 'Ovolactovegetariano',
    non_veg: 'No Vegetariano',
    start_workout: 'Empezar Entrenamiento',
    exercises: 'Ejercicios',
    sets: 'Series',
    reps: 'Repeticiones',
    rest_sec: 'Descanso (seg)',
    bodyweight: 'Peso Corporal',
    dumbbells: 'Mancuernas',
    gym: 'Gimnasio',
    resistance_bands: 'Bandas',
    fat_loss: 'Pérdida de Grasa',
    muscle_gain: 'Ganancia Muscular',
    recomp: 'Recomposición Corporal',
    pcod_control: 'Control Hormonal',
    workout_completed: '¡Entrenamiento Completado!',
    total_calories_burned: 'Total de Calorías Quemadas',
    hydration_reminder: '¡Hora de beber un vaso de agua!',
    meal_reminder: '¡Hora de tu comida saludable!',
    session_restored: '¡Bienvenido de nuevo! Tu sesión está activa.',
  },

  fr: {
    home: 'Accueil',
    meal_plan: 'Repas',
    workout: 'Entraînement',
    swaps: 'Échanges Intelligents',
    analytics: 'Progression',
    settings: 'Paramètres',
    profile: 'Profil',
    namaste: 'Bonjour',
    guest_mode: 'Mode Invité',
    sign_in: 'Connexion',
    sign_up: "S'inscrire",
    sign_out: 'Déconnexion',
    save_changes: 'Enregistrer',
    app_language: "Langue de l'application",
    select_language_desc: 'Sélectionnez votre langue préférée',
    stay_logged_in: 'Rester Connecté',
    verified_member: 'Membre Vérifié',
    cloud_synced: 'Synchronisé sur le Cloud',
    daily_energy_balance: 'BILAN ÉNERGÉTIQUE QUOTIDIEN',
    log_meal: 'Ajouter un Repas',
    quick_add: 'Ajout Rapide',
    water_tracker: 'HYDRATATION QUOTIDIENNE',
    water_glasses: "Verres d'Eau",
    target: 'Objectif',
    remaining: 'Restant',
    consumed: 'Consommé',
    burned: 'Brûlé',
    calories: 'Calories',
    protein: 'Protéines',
    carbs: 'Glucides',
    fat: 'Lipides',
    katoris: 'Portions',
    phulkas: 'Rotis / Pains',
    desi_ghee: 'Ghee Pur',
    add_to_diary: 'Ajouter au Journal',
    calories_left: '{{count}} kcal restantes aujourd’hui',
    protein_left: '{{count}}g de protéines restantes',
    glasses_remaining: '{{count}} verres restants',
    master_diet_chart: 'Plan Diététique Personnalisé',
    diet_chart_sub: 'Adapté à votre cuisine et vos objectifs',
    swap_dish: 'Changer de Plat',
    view_recipe: 'Voir la Recette',
    portion: 'Portion',
    cost: 'Coût Estimé',
    breakfast: 'Petit-déjeuner',
    lunch: 'Déjeuner',
    evening_snack: 'Collation',
    dinner: 'Dîner',
    custom_meal: 'Repas Personnalisé',
    search_food: 'Rechercher un Aliment...',
    recent_entries: 'Derniers Repas',
    saved_meals: 'Repas Enregistrés',
    save_custom_meal: 'Enregistrer le Repas',
    repeat_meal: 'Répéter',
    pure_veg: 'Végétarien Pur',
    jain: 'Régime Jain',
    eggetarian: 'Ovo-végétarien',
    non_veg: 'Non-végétarien',
    start_workout: "Démarrer l'Entraînement",
    exercises: 'Exercices',
    sets: 'Séries',
    reps: 'Répétitions',
    rest_sec: 'Repos (sec)',
    bodyweight: 'Poids du Corps',
    dumbbells: 'Haltères',
    gym: 'Salle de Sport',
    resistance_bands: 'Bandes Élastiques',
    fat_loss: 'Perte de Gras',
    muscle_gain: 'Prise de Muscle',
    recomp: 'Recomposition Corporelle',
    pcod_control: 'Équilibre Hormonal',
    workout_completed: 'Entraînement Terminé !',
    total_calories_burned: 'Total des Calories Brûlées',
    hydration_reminder: "C'est l'heure de boire un verre d'eau !",
    meal_reminder: "C'est l'heure de votre repas équilibré !",
    session_restored: 'Bon retour ! Votre session est active.',
  },
};

interface LanguageContextType {
  language: AppLanguage;
  availableLanguages: LanguageMeta[];
  currentLanguageMeta: LanguageMeta;
  setLanguage: (lang: AppLanguage) => Promise<void>;
  t: (key: string, defaultText?: string, params?: Record<string, string | number>) => string;
  getLocalizedFoodName: (food: FoodItemTranslatable | string | undefined | null) => string;
  formatRupees: (amount: number) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  availableLanguages: AVAILABLE_LANGUAGES,
  currentLanguageMeta: AVAILABLE_LANGUAGES[0],
  setLanguage: async () => {},
  t: (_key: string, defaultText?: string) => defaultText || '',
  getLocalizedFoodName: (food) => {
    if (!food) return '';
    return typeof food === 'string' ? food : food.name || '';
  },
  formatRupees: (amount) => `₹${amount}`,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<AppLanguage>('en');

  useEffect(() => {
    (async () => {
      try {
        const savedLang = await SafeStorage.getItem('mealfit_language');
        if (savedLang && AVAILABLE_LANGUAGES.some((l) => l.code === savedLang)) {
          setLanguageState(savedLang as AppLanguage);
        }
      } catch (err) {
        console.log('[LanguageContext] Failed to load language:', err);
      }
    })();
  }, []);

  const setLanguage = async (lang: AppLanguage) => {
    setLanguageState(lang);
    try {
      await SafeStorage.setItem('mealfit_language', lang);
    } catch (err) {
      console.warn('[LanguageContext] Failed to persist language:', err);
    }
  };

  /**
   * Advanced translation helper with fallback and dynamic parameter replacement.
   * Example: t('calories_left', '{{count}} kcal left today', { count: 400 })
   */
  const t = (
    key: string,
    defaultText?: string,
    params?: Record<string, string | number>
  ): string => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
    let template = dict?.[key] || TRANSLATIONS.en?.[key] || defaultText || key;

    if (params && typeof template === 'string') {
      Object.entries(params).forEach(([paramKey, paramVal]) => {
        template = template.replace(new RegExp(`{{${paramKey}}}`, 'g'), String(paramVal));
      });
    }

    return template;
  };

  /**
   * Returns a single clean, localized food title based on the active language.
   * Avoids concatenation or dual language clutter.
   */
  const getLocalizedFoodName = (food: FoodItemTranslatable | string | undefined | null): string => {
    if (!food) return '';
    if (typeof food === 'string') return food.trim();

    // Check regional specific dictionary override
    if (food.regionalNames && food.regionalNames[language]) {
      const reg = food.regionalNames[language];
      if (reg && reg.trim().length > 0) return reg.trim();
    }

    if (language === 'hi' && food.hindiName && food.hindiName.trim().length > 0) {
      return food.hindiName.trim();
    }
    if (language === 'hinglish' && food.hinglishName && food.hinglishName.trim().length > 0) {
      return food.hinglishName.trim();
    }
    return (food.name || food.hindiName || '').trim();
  };

  const formatRupees = (amount: number): string => {
    return `₹${Math.round(amount)}`;
  };

  const currentLanguageMeta =
    AVAILABLE_LANGUAGES.find((l) => l.code === language) || AVAILABLE_LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        language,
        availableLanguages: AVAILABLE_LANGUAGES,
        currentLanguageMeta,
        setLanguage,
        t,
        getLocalizedFoodName,
        formatRupees,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
